Update __init__.py
Using interface table() and then execute() like the following codes will get a KeyError: 

import ibis
hdfs = ibis.impala.hdfs_connect(host='kudu1')
on = ibis.impala.connect(host='kudu3', port=10000, database='yy_test', user='us', hdfs_client=hdfs, kerberos_service_name=None, auth_mechanism='PLAIN')
res = on.table('employee').execute()

the error:
Traceback (most recent call last):
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'shop_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/edy/src/PythonProjects/dt-center-algorithm/test/1.py", line 10, in <module>
    res = on.table('employee').execute()
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/expr/types.py", line 274, in execute
    self, limit=limit, timecontext=timecontext, params=params, **kwargs
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/backends/base/sql/__init__.py", line 126, in execute
    result = self.fetch_from_cursor(cursor, schema)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/backends/impala/__init__.py", line 318, in fetch_from_cursor
    return schema.apply_to(df)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/ibis/expr/schema.py", line 175, in apply_to
    col = df[column]
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'shop_id'

I found the queried result about columns contains the table name, but there is no table name in 'df'. So I think it is a bug about interface get_schema(). I made a pr.  tks